### ISSUE TITLE
Don't work with internal properties

### ISSUE THREAD

**Issue by MikaelWilen** [jamesfoster/DeepEqual#13]
If my TestClass has public properties it works but when they are sat as internal DeepEquels no longer find any differences. 

 public class TestClass
    {        
         internal int TestInt { get; set; }
         internal string TestString { get; set; }
    }

    [TestFixture]
    public class TestClassTest
    {

        [Test]
        public void SerTest()
        {
            var testA = new TestClass() {TestInt = 1, TestString = "A"};
            var testB = new TestClass() { TestInt = 2, TestString = "B" };

            testA.ShouldDeepEqual(testB);
            Assert.DoesNotThrow(() => testA.ShouldDeepEqual(testB));
            Assert.IsTrue(testA.IsDeepEqual(testB));
        }
    }

**Comment by jamesfoster** [comment]
If you want to compare the internals of 2 objects the best option at the moment is probably to implement a custom `IComparer` and pass it in as the second parameter to `ShouldDeepEqual` / `IsDeepEqual`.

To build a full chain of comparisons, use

    new ComparisonBuilder()
      .WithCustomComparison(mine)
      .Create()`

How would to see exposing internals working?

I'm reluctant to make it the default behaviour, mainly because it would be a breaking change. I can suggest the following syntax:

    actual
      .WithDeepEqual(expected)
      .ExposeInternalsOf<SomeType>()
      .Assert()

What do you think?

**Comment by MikaelWilen** [comment]
Hi James,
Thanks for your answer.

In version 1.0 both IsDeepEqual and ShouldDeepEqual works with internal properties.
Version 1.1 IsDeepEqual works but not ShouldDeepEqual.
Version 1.1.1 neither works with internal properties.

So there have been a breaking change already in the behavior.

I don’t want to implement IComparer to make it possible to check if the instances have the same values. If that is needed then the use of DeepEqual is unnecessary for me. Your suggestion of the syntax  .ExposeInternalsOf<SomeType>() how would that work when you have a large tree structure with an array of different types that you want to compare?
Would it be possible to have something like .IncludeInternals() that whould include the internals in all checks?

Regards,
Mikael Wilen

**Comment by jamesfoster** [comment]
Thanks for pointing this out. I've just pushed a fix for the discrepancies between `IsDeepEqual` and `ShouldDeepEqual`.

I've also added the `ExposeInternalsOf` method with an overload that takes a list of types. It's really not desirable to compare the internals of all types as you'll end up comparing internals of the built in .NET types.
