### ISSUE TITLE
Cannot install from 1.2 to 1.4 on Visual Studio 2015

### ISSUE THREAD

**Issue by yukoba** [jamesfoster/DeepEqual#14]
I cannot install from 1.2 to 1.4 by the NuGet package manager on Visual Studio 2015 CTP 6.
I can install 1.1.1. I also can install by Visual Studio 2013.

![2015-03-27 04 06 46](https://cloud.githubusercontent.com/assets/194666/6854791/c11e0a02-d436-11e4-8da0-f4311b6e7085.png)

**Comment by jamesfoster** [comment]
Ok. I'll check it out. Thanks for reporting if.

**Comment by jamesfoster** [comment]
Packages 1.2 to 1.4 were created using the latest stable version of nuget. version 2.8.3.

I've just checked and these packages are almost identical to the previous packages. The only difference I can see is they have an extra node in the core-properties file

```
<lastModifiedBy>NuGet, Version=2.8.50926.602, Culture=neutral, PublicKeyToken=null;Microsoft Windows NT 6.2.9200.0;.NET Framework 4</lastModifiedBy>
```

I currently don't have the latest VS2015 CTP installed so I can't test it, but this must somehow be causing an issue with that version of nuget.

This seems like an odd backward compatibility issue with nuget. Could you check to see if there's been an update to nuget, see if that fixes your issue?

If not, I've created a package based on 1.4 which doesn't have the `lastModifiedBy` node. I've set it as a prelease version. so if you try `Install-Package DeepEqual -Pre` let me know if that works and I'll make it the next stable version.

Thanks

**Comment by yukoba** [comment]
> NuGet 3.0 Beta was released on February 23, 2015 for the Visual Studio 2015 CTP 6 release. 
http://docs.nuget.org/release-notes/nuget-3.0-beta

>  Could you check to see if there's been an update to nuget, see if that fixes your issue?

My NuGet version is 3.0.0.0 and I was using API v3 for NuGet.
I tried to install DeepEqual.1.4.0.1-rc, but nothing changed.

If I change to API v2 for NuGet, I can install 1.4.0.
What is changed on API v3?

**Comment by jamesfoster** [comment]
I've raised the issue with nuget here https://github.com/NuGet/NuGetGallery/issues/2388

I'm closing this as it isn't a problem with the DeepEqual source, or how the packages were created. Perhaps the metadata is out of sync in v3 of the nuget API?

**Comment by jamesfoster** [comment]
@yukoba Would you be able to give me the full stack trace? you might get this using the Package Manager Console instead of the GUI!

Cheers

James

**Comment by yukoba** [comment]
OK. I pasted to https://github.com/NuGet/NuGetGallery/issues/2388.

**Comment by jamesfoster** [comment]
Thanks :)
