### ISSUE TITLE
DateTime comparisons failing

### ISSUE THREAD

**Issue by Jonathan-Turner** [jamesfoster/DeepEqual#15]
Good evening,

Apologies if this is addressed somewhere and I have missed it. DateTime value comparison doesn't appear to be happy, see below. Before finding DeepEqual I had to compare them after calling ToString() and comparing the string contents. Hopefully I'm just missing something

```
DeepEqual.Syntax.DeepEqualException : Comparison Failed: The following 2 differences were found.
	Actual.DateCreated != Expected.DateCreated (9/7/2015 9:57:38 PM != 9/7/2015 9:57:38 PM)
	Actual.LastModified != Expected.LastModified (9/7/2015 9:57:38 PM != 9/7/2015 9:57:38 PM)
```

**Comment by jamesfoster** [comment]
I'll check it out. Can you verify that the Ticks of both dates are the same?

**Comment by Jonathan-Turner** [comment]
Good question, let me verify. I am integration testing an insert and select from SQL Server... but am not currently specifying ticks. Let me go down that path a bit and I will update the issue.

**Comment by Jonathan-Turner** [comment]
Thanks for pointing me in the right direction James. I was saving only up through seconds but comparing it against DateTime.Now which had milliseconds etc as well. 

Closing this out, sorry for the false positive.

Awesome job on the project!

**Comment by jamesfoster** [comment]
No problem.
