### ISSUE TITLE
NullReferenceException on equal objects in massive multithreaded scenario

### ISSUE THREAD

**Issue by llehn** [jamesfoster/DeepEqual#17]
I occasionaly get a NullreferenceException where there should be none.
I guess the RelfectionCache is not thread-safe, has some kind of racing condition.
Attached screenshot show stack trace and the objects to be compared.
Version 1.4

![2016-01-12 23_30_43-globalpic debugging - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/10240910/12278980/8eeea0d0-b984-11e5-983d-c4974be0eebc.jpg)

**Comment by jamesfoster** [comment]
Thanks. You're probably right about thread safety. I'll take a look.

**Comment by jamesfoster** [comment]
Ok. Give version 1.5 a go. Let me know if you have any more issues. I'll close this for now but if there's still a problem I'll reopen it.

**Comment by llehn** [comment]
Thanks you! Confirming works for me!
