### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ToXinE** [jamesfoster/DeepEqual#18]
Hi, 
I want to use your library but I'm not able to ignore some properties in the following way (i guessed).

`
content.WithDeepEqual(expected).IgnoreSourceProperty(x => x.InfoContrat.PerfP).Assert();
`
This is the only property i don't want to compare.

Is this the good way to go ?

Where can i have some more documentation / examples ?

(my actual and expected objects are way too big to paste here)

**Comment by jamesfoster** [comment]
You can try:

IgnoreProperty<MyClass>(x => x.PerfP)

This will ignore this properties on all objects in the graph of that type.

**Comment by jamesfoster** [comment]
The documentation is the tests. :)

https://github.com/jamesfoster/DeepEqual/blob/master/src/DeepEqual.Test/Comparsions/ComplexObjectComparisonTests.cs

**Comment by ToXinE** [comment]
Thank you :+1: !
A quick explanations of basic functions can be useful and it can spare some times browsing all the tests :)
