### ISSUE TITLE
An expression tree may not contain a call or invocation that uses optional arguments

### ISSUE THREAD

**Issue by dstj** [jamesfoster/DeepEqual#19]
After updating to DeepEqual 1.5.0, I have numerous errors stating: `An expression tree may not contain a call or invocation that uses optional arguments` with lines like the following 

```
_repository.Received().Update(Arg.Is<MyClass>(obj => obj.IsDeepEqual(expected)));
````
It's a NSubstitute test. I'm forced to add an extra NULL parameter to all my mock asserts:

```
_repository.Received().Update(Arg.Is<MyClass>(obj => obj.IsDeepEqual(expected, null)));
```

Could `IsDeepEqual` use an overload instead of an optional parameter?

Thanks.

**Comment by jamesfoster** [comment]
Done. Check out version 1.5.1
