### ISSUE TITLE
Refactor extensions on object

### ISSUE THREAD

**Issue by KristianWedberg** [jamesfoster/DeepEqual#21]
The library has several extension methods on object (WithDeepEqual etc.) This makes them pollute Intellisense for _all_ class objects, which is quite annoying.

I suggest refactoring to instead use non-extension methods, e.q. DeepEqual.IsEqual(ob1, ob2) etc.

**Comment by jamesfoster** [comment]
Its done that way to make your tests more readable. The same way Shouldly adds `ShouldEqual` etc to Object. This won't change.
