### ISSUE TITLE
Nested properties are not ignored.

### ISSUE THREAD

**Issue by JoshMcCullough** [jamesfoster/DeepEqual#24]
When attempting to ignore a nested property, it is still being considered during the comparison:

```
actual.WithDeepEqual(expected)
    .IgnoreSourceProperty(o => o.SomeProperty.ChildProperty)
    .Assert();
```

This still throws an exception when `SomeProperty.ChildProperty` is different. Perhaps this is simply not supported?

**Comment by jamesfoster** [comment]
I don't believe this is implemented. You *can* ignore a property on all instances of a known type...

`.IgnoreProperty<InnerType>(x -> x.ChildProperty)`

Does this suffice?

**Comment by JoshMcCullough** [comment]
That would likely work for my case, thanks. May be a good feature to consider for the future, though. Will leave that up to you! :)

**Comment by TAGC** [comment]
Aye ignoring nested properties would be nice
