### ISSUE TITLE
Should be strong signed

### ISSUE THREAD

**Issue by ilyalatt** [jamesfoster/DeepEqual#26]
<img width="512" alt="screen shot 2017-10-10 at 16 40 47" src="https://user-images.githubusercontent.com/20675149/31389521-e809c690-add9-11e7-8bc0-edc1b6644a14.png">

**Comment by obok** [comment]
@jamesfoster having NuGet package signed would be really useful. 
In my case tested project is signed and to test internal classes I'm using InternalsVisibleTo attribute. This forces me to have also test projects signed. To sign test project its all dependencies has to signed including DeepEqual.

**Comment by jamesfoster** [comment]
Version 1.7.1 should now be strong signed
