### ISSUE TITLE
compare enums via string match

### ISSUE THREAD

**Issue by DmitryBryluk** [jamesfoster/DeepEqual#28]
is it possible some option to compare enums via string match?

when there are two different classes with the same structure and content, comparison is ok, except enums

upd: seems possible with custom comparison, but nice to have option

**Comment by jamesfoster** [comment]
This is already available.

https://github.com/jamesfoster/DeepEqual/blob/master/src/DeepEqual.Test/Comparsions/EnumComparisonTests.cs#L131
