### ISSUE TITLE
option for case-insensitive member name match

### ISSUE THREAD

**Issue by DmitryBryluk** [jamesfoster/DeepEqual#29]
is there some option for case-insensitive member name match?
i.e. Class1.ID match with Class2.id

also custom property matcher and/or regex pairs to match property names will be nice

with regex pairs: [/id/i, /(primary_?)?id/i] will match Class1.{id|ID|Id|...} to Class2.{id|ID|Id|PrimaryId|primary_id|...}

**Comment by jamesfoster** [comment]
In this case I would recommend writing a custom comparison.

```
	object1
		.WithDeepEqual(object2)
		.WithCustomComparison(new CustomComparison())
		.Assert();
```
