### ISSUE TITLE
Only get difference without assert

### ISSUE THREAD

**Issue by jim-molecule** [jamesfoster/DeepEqual#32]
Can I get difference between two objects without throw new DeepEqualException?
Method ‘ShouldDeepEqual’ returns good message with difference, but it creates exception.

**Comment by jamesfoster** [comment]
Currently there's no nice API to get the difference. However, you could make your own extension method that did something similar to `ShouldDeepEqual`

https://github.com/jamesfoster/DeepEqual/blob/cf978792b5ec0642be6a84a1f0c28b5ca37784b1/src/DeepEqual/Syntax/ObjectExtensions.cs#L37

```
		public static void DeepEqualityMessage(
			this object actual,
			object expected,
			IComparison comparison,
			IDifferenceFormatterFactory formatterFactory)
		{
			var builder = new ComparisonBuilder();

			comparison = comparison ?? builder.Create();
			formatterFactory = formatterFactory ?? builder.GetFormatterFactory();

			var context = new ComparisonContext();

			var (result, newContext) = comparison.Compare(context, actual, expected);

			if (result != ComparisonResult.Fail)
			{
				return string.Empty;
			}

			var message = new DeepEqualExceptionMessageBuilder(newContext, formatterFactory).GetMessage();

			return message;
		}
```

**Comment by jamesfoster** [comment]
Out of interest, what is your use case?

**Comment by jim-molecule** [comment]
During test I check difference between variables several time. If difference founded I add it to error list. In the end of test I check that error list is empty.

**Comment by jamesfoster** [comment]
Closing this. If you feel there's a strong case to add this to the library we can reopen it and discuss.
