### ISSUE TITLE
Bypass Equals implementations on classes

### ISSUE THREAD

**Issue by asgerhallas** [jamesfoster/DeepEqual#36]
I'm using DeepEqual for unit testing, and I would like to make a comparison of two class instances, that has a custom implementation of Equals, that compares only on a subset of the objects properties. 

Is it possible to configure DeepEqual to not use the Equals method for comparison on class types (not strings), and thus always fall back to complex object comparisons for these?

And if not, would it be a welcome addition to the library?

**Comment by jamesfoster** [comment]
Sure, this is possible using the `SkipDefault<T>()` method

```
object1
  .WithDeepEqual(object2)
  .SkipDefault<T>()
  .Assert();
```

**Comment by jamesfoster** [comment]
The other option you have is to create a custom comparison. All custom comparisons execute before the built in ones so you can prevent the default from executing that way.

```
object1
  .WithDeepEqual(object2)
  .WithCustomComparison(new MyComparison())
  .Assert()
```

**Comment by jamesfoster** [comment]
Alternate syntax for the above:

```
var comparison = new ComparisonBuilder()
  .SkipDefault<T>()
  .Build();

object1.ShouldDeepEqual(object2, comparison);
```

**Comment by asgerhallas** [comment]
Thank you. I should have written, what I already tried... I used it like this:

```
var comparison = new ComparisonBuilder()
  .SkipDefault<object>()
  .Build();

object1.ShouldDeepEqual(object2, comparison);
```

And thought that it might skip Equals call for all objects then... but that did not work as expected. It works for other base classes though, so I guess I can make it through :)
