### ISSUE TITLE
NaN support

### ISSUE THREAD

**Issue by vilinski** [jamesfoster/DeepEqual#38]
Trying to run a property test using FsCheck. It generates also NaN for double values. Normally is always NaN != NaN, but for equality it doesn't matter. Is there any option for it or is it possible to convince DeepEqual to take NaNs as equal?

**Comment by jamesfoster** [comment]
Interesting. Conceptually, not all `NaN`s are equal. Division by zero and the log of a negative number both return `NaN` but they are not the "same".

You can always write your own Comparison that deals with `NaN` the way you want.

Either:

```
var comparison = new ComparisonBuilder()
    .WithCustomComparison(new NaNComparison())
    .Build();

myObject1.ShouldDeepEqual(myObject2, comparison);
```

Or:

```
myObject1
    .WithDeepEqual(myObject2)
    .WithCustomComparison(new NaNComparison())
    .Assert()
```
