### ISSUE TITLE
Consider implementing equality for System.Text.Json.JsonDocument

### ISSUE THREAD

**Issue by sergeyt** [jamesfoster/DeepEqual#43]

**Comment by programmerbits** [comment]
Was just looking for something to help with this.  I have a versioned asp.net API.  I wanted to write a test for an old version of the API where I send in some JSON and check the JSON response to help make sure that I don't accidentally do something to break the old version of the API.

**Comment by jamesfoster** [comment]
Added in version 3.0.0 as a separate Nuget package.
