### ISSUE TITLE
Is it possible to setup a map for properties?

### ISSUE THREAD

**Issue by the-dext** [jamesfoster/DeepEqual#51]
Hi, 
Great library, thanks for putting this together.

Do you know if it's possible to setup an exception to the user comparison of matching properties so that if a property has been renamed we can check the objects were copied properly ?

for example. imagine type 1 has a 'lastName' property, and type 2 has a 'surname' property. 
Could we do something like 'mapProperty(x=> x.lastName, y=> y.surname)' ?

Thanks.

**Comment by jamesfoster** [comment]
It's certainly possible but the answer is to write your own comparison.

```c#
public class PersonComparison : IComparison
{
  public bool CanCompare(Type type1, Type type2) => type1 == typeof(Person) && type2 == typeof(Employee);

  public (ComparisonResult result, IComparisonContext context) Compare(
    IComparisonContext context,
    object value1,
    object value2
  ) {
    var person = (Person) value1;
    var employee = (Employee) value2;

    // if you find a difference
    return (ComparisonResult.Fail, context.AddDifference(new PersonDifference("Surname", person.Surname, "LastName", employee.LastName));

    // if the objects are the same
    return (ComparisonResult.Pass, context);
  }
}
```

The default DifferenceFormatter doesn't account for mismatched property names. If you use a custom difference as above you should register a custom formatter.

```c#
a.WithDeepEqual(b)
    .WithCustomComparison<PersonComparison>()
    .WithCustomFormatter<PersonDifference>(new PersonDifferenceFormatter())
    .Assert();
```
