### ISSUE TITLE
Comparing `IEnumerable`s without regards to order (without throwing)

### ISSUE THREAD

**Issue by ruffin--** [jamesfoster/DeepEqual#53]
I have a use case where I want to compare two collections of entities (specific class type here is a custom in-house class, `Answer`; it could be anything) and see if they are equal without concern for the order. The collections are `IEnumerable`, so I can't count on a specific ordering, which also means I don't want my equality check to care about order. Right now, I've getting failures in DeepEqual where essentially it's telling me `value1[0] != value2[0]`, but `value1[1] == value2[0]` and vice versa for 2 two-element collections.

I need to fix that.

I'd hoped to create collections that are ordered (by `Id` in this case) in my custom `Compare` and then compare, but obviously the only really important idea is that they are matchable in some way that allows equality checks.

Right now I'm using code like the following in a custom `IComparison`:

```
public (ComparisonResult result, IComparisonContext context) Compare(IComparisonContext context, object value1, object value2)
{
	var custom1 = (IEnumerable<Answer>)value1;
	var custom2 = (IEnumerable<Answer>)value2;

        // Ob could add to the lines above
	var ordered1 = custom1.ToList();
	var ordered2 = custom2.ToList();

	ordered1.Sort((a, b) => a.Id.CompareTo(b.Id));
	ordered2.Sort((a, b) => a.Id.CompareTo(b.Id));

	// I haven't found a good way to return the description.
	// I can pull from the exception thrown by ShouldDeepEqual,
	// but that apparently leaves the app in an residual
	// exception-has-been-thrown state that gets ugly?
	if (!ordered1.IsDeepEqual(ordered2))
	{
	    context.AddDifference(value1, value2);
	    return (ComparisonResult.Fail, context);
	}

	return (ComparisonResult.Pass, context);
}
```

The comments kind of tell the tale. If I capture a throw (by using `ShouldDeepEqual` instead of `IsDeepEqual`), I get some text I might be able to output somewhere, but I didn't seem to be able to attach it to `AddDifference`. So for the time being I'm checking the `IsDeepEqual` boolean and returning the right `ComparisonResult` value without a good message.

There is an `AddDifference` overload that has a string as the third parameter, but that's for the field that's failing, and it didn't display text especially cleanly when it failed.

What's the right way to compare `IEnumerable<T>`?

**Comment by atif1996** [comment]
Have the same problem here, but in my case, I can turn them into Sets.  So 
`
bool equivalent = first.ToHashSet().SetEquals(second.ToHashSet());
`
Just looking at using DeepEqual under the covers.

**Comment by jamesfoster** [comment]
DeepEqual already does Set quality if one of the sides is an `ISet<T>`
